### ISSUE TITLE
Inlining

### ISSUE THREAD

**Issue by jadr2ddude** [dibyendumajumdar/ravi#96]
I created a performance test program for function calls in ravi. It did not turn out well. Do you inline function calls in ravi? If not, this could be done using a conditional that would check if a function has been modified. If not modified, it could call the inline version, and if it was it could call the modified version. LLVM should be able to optimize the conditional out.

Here is the test: (github won't let me upload with a .lua extension)

[gravity.txt](https://github.com/dibyendumajumdar/ravi/files/362684/gravity.txt)

**Comment by dibyendumajumdar** [comment]
Hi, inlining is a hard problem for which I need to implement a new parser and code generator. I did start on this but it is not something I have enough time to look into.

Llvm can't help as the problem is that inlining has to occur at Lua source level.
From: jadr2ddude
Sent: Wednesday, 13 July 2016 11:46 PM
To: dibyendumajumdar/ravi
Reply To: dibyendumajumdar/ravi
Subject: [dibyendumajumdar/ravi] Inlining (#96)



I created a performance test program for function calls in ravi. It did not turn out well. Do you inline function calls in ravi? If not, this could be done using a conditional that would check if a function has been modified. If not modified, it could call the inline version, and if it was it could call the modified version. LLVM should be able to optimize the conditional out.

Here is the test: (github won't let me upload with a .lua extension)

gravity.txt<https://github.com/dibyendumajumdar/ravi/files/362665/gravity.txt>

-

**Comment by dibyendumajumdar** [comment]
Linked to issue #98

**Comment by dibyendumajumdar** [comment]
A new project that is doing inlining at bytecode level.
https://github.com/Nymphium/opeth
